services:
  iptables-web-ui:
    container_name: iptables-web-ui
    image: iptables-web-ui:latest
    network_mode: host
    cap_add:
     - NET_ADMIN
    environment:
      - TZ=<timezone>
      - WEBUI_PASSWORD=<my_password>
    restart: unless-stopped
